# Generated by Django 4.2.3 on 2023-08-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretotype", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="referer",
            field=models.CharField(max_length=32, null=True, verbose_name="referer"),
        ),
    ]
